"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var langs_1 = require("./langs");
exports.languages = langs_1.default;
var plugins_1 = require("./plugins");
exports.plugins = plugins_1.default;
var themes_1 = require("./themes");
exports.themes = themes_1.default;
var prism_1 = require("./prism");
exports.default = prism_1.default;
